locale = {"generic_error":"An error occurred during the processing of the command: {}",
"no_dev":"You are not a Xyn developer!",
"cooldown":"This command is on cooldown. Retry in ",
"no_permission":"You don't have permission to run this command!",
"banned":"Banned {}.\n**Reason** ",
"no_reson_ban":"No reason provided",
"only_server_command":"This command can only be used in a server",
"purged":"Purged {} messages",
"too_old":"Couldn't find any messages younger than 14 days!",
"renamed_user":"User <@{}> was renamed to {}",
"no_permission_rename":"Xyn doesn't have permission to rename this user",
"xyn_no_permission":"Xyn does not have permission to do this!",
"added_spotify":"Added {} songs from Spotify!",
"music_not_found":"Music not found",
"generic_error_music":"Track failed to load, try again later\n{}",
"playlist_added":"Added {} tracks to the queue",
"no_voice":"You need to be in a voice channel to use this command!",
"added_queue":"Added to queue:\n[{}]({})",
"not_playing":"There's nothing playing!",
"yet":"yet...",
"not_playing_tease":"Maybe you could change that ;)",
"now_playing":"Now Playing...\n[{}]({})",
"skipped_music":"Skipped to the next song:\n [{}]({})",
"resumed_music":"The playback was resumed!",
"volume_set":"Volume set to {}%",
"paused":"{title} was paused!",
"stuck":"Well, I guess I'm stuck",
"music_stop":"Okay! Stopped the playback",
"generic_player_error":"Unfortunately there was an fatal error initializing the player, please try again later",
"reddit_not_found":"An error occurred trying to fetch a post from your desired subreddit, maybe check your spelling or try again later",
"generic_reddit_error":"Error getting the sub",
"no_nsfw":"The safe mode can only be turned off inside an NSFW channel!",
"uwu_no_lang":"Unfowtunyatewy this c-c-command isn't avaiabwe in youw wanguage!",
"uwu_enabled":"the sewvew uwuify OwO is enyabwed!!11 Enjoy youw puwwfect  expewience OwO",
"uwu_disabled":"The server uwuify was disabled! Everything is now back to normal!",
"no_banner":"This user has no banner!",
"no_pfp":"This user has no pfp!",
"set_language":"The guild language was successfully set to {}!",
"command_error":"An error occurred during the processing of the command: `{}`!",
"youtube_client":"The guild's YouTube client was set to {}!",
}