locale = {"generic_error":"コマンドの処理中にエラーが発生しました: {}",
"no_dev":"あなたは Xyn 開発者ではありません!",
"cooldown":"このコマンドはクールダウン中です。",
"no_permission":"このコマンドを実行する権限がありません!",
"banned":"{} は {} のために禁止されました",
"no_reson_ban":"理由が提供されていません",
"only_server_command":"このコマンドはサーバーでのみ使用できます",
"purged":"{} 件のメッセージをパージしました",
"too_old":"14 日以内のメッセージは見つかりませんでした!",
"renamed_user":"ユーザー <@{}> の名前が {} に変更されました",
"no_permission_rename":"Xyn には、このユーザーの名前を変更するための十分な権限がありません",
"added_spotify":"Spotify から {} 曲を追加しました!",
"music_not_found":"音楽が見つかりません",
"generic_error_music":"トラックを読み込めませんでした。後で再試行してください\n{}",
"playlist_added":"キューに{}曲が追加されました",
"no_voice":"このコマンドを使用するには、ボイス チャネルにいる必要があります!",
"added_queue":"キューに追加:\n[{}]({})",
"not_playing":"再生中の曲はありません",
"yet":"それを変えたらどうですか?",
"not_playing_tease":"o_o",
"now_playing":"再生中...\n[{}]({})",
"skipped_music":"次の曲にスキップしました:\n [{}]({})",
"resumed_music":"再生が再開されました!",
"volume_set":"音量を {}% に設定",
"paused":"{title} が一時停止されました!",
"stuck":"ええと...私は立ち往生していると思います",
"music_stop":"わかった！ 再生を停止しました",
"generic_player_error":"残念ながら、プレーヤーの初期化中に致命的なエラーが発生しました。後でもう一度お試しください",
"reddit_not_found":"目的のサブレディットから投稿を取得しようとしてエラーが発生しました。スペルを確認するか、後でもう一度お試しください",
"generic_reddit_error":"Error getting the sub",
"no_nsfw":"セーフ モードは、NSFW チャネル内でのみオフにすることができます!",
"uwu_no_lang":"残念ながら、このコマンドはあなたの言語では利用できません!",
"no_banner":"ユーザーにはバナーがありません!",
"no_pfp":"ユーザーにはプロフィール写真がありません!",
"set_language":"ギルド言語は次のように定義されました: {}!",
"command_error":"コマンドの処理中にエラーが発生しました: `{}`",
"youtube_client":"The guild's YouTube client was set to {}!",
}