locale = {"generic_error":"Um erro ocorreu ao processar o comando: {}",
"no_dev":"Você não é um desenvolvedor(a) do Xyn",
"cooldown":"Esse comando está em cooldown. Tente novamente em: ",
"no_permission":"Você não tem permissão para usar esse comando",
"banned":"{} Foi banido!.\n**Por** ",
"no_reason_ban":"Nenhuma razão foi dada!",
"only_server_command":"Esse comando só pode ser utilizado dentro de uma guild",
"purged":"Foram deletadas {} mensagens",
"too_old":"Não foi possível achar mensagens mais recentem que 14 dias!",
"renamed_user":"O usuário <@{}> foi renomeado para {}",
"no_permission_rename":"Xyn não tem permissão para renomear esse usuário",
"added_spotify":"Foram adicionadas {} músicas do Spotify!",
"music_not_found":"Música não encontrada",
"generic_error_music":"A música falhou ao carregar, tente novamente mais tarde\n```{}```",
"playlist_added":"Foram adicionadas {} músicas à fila",
"no_voice":"Você precisa estar conectado à um canal de voz para usar esse comando!",
"added_queue":"Foi adicionado à fila:\n[{}]({})",
"not_playing":"Não há nada tocando!",
"yet":"ainda...",
"not_playing_tease":"Talvez você possa fazer algo sobre ;)",
"now_playing":"Atualmente tocando...\n[{}]({})",
"skipped_music":"O playback foi pulado para a próxima música:\n[{}]({})",
"resumed_music":"O playback foi resumido",
"volume_set":"O volume foi definido: {volume}%",
"paused":"{title} foi pausado!",
"stuck":"Eh, Acho que estou preso",
"music_stop":"Okay! Parei o playback",
"generic_player_error":"Infelizmente ocorreu um erro fatal ao inicializar o player, por favor tente novamente mais tarde",
"reddit_not_found":"Um erro ocorreu ao tentar buscar um post de seu subreddit desejado, cheque se o nome foi escrito corretamente e tente novamente",
"generic_reddit_error":"Erro ao buscar o subreddit",
"no_nsfw":"O safe mode só pode ser desligado em um canal NSFW!",
"uwu_no_lang":"Infewizmente esse comando não está disponyivew em seu idioma!",
"uwu_enabled":"O uwuify gwobaw OwO foi ativado nyo sewvew, apwuvite >.<",
"uwu_disabled":"O uwuify global foi desativado! Tudo voltou ao normal!",
"no_banner":"O usuário não tem um banner!",
"no_pfp":"O usuário não tem uma foto de perfil!",
"set_language":"O idioma do servifor foi definido como: {}",
"command_error":"Um erro ocorreu ao executar o comando `{}`!",
}
