locale = {"generic_error":"An ewwow occuwed duwing the pwocessing of the command: ",
"no_dev":"You'we nyot a Xyn devewopew *blushes*",
"cooldown":"This c-c-command is on coowdown. Wetwy in ",
"no_permission":"You don't have pewmission t-to wun this commmand?!?!",
"banned":"B-B-Bannyed {}.\n**Weason** ",
"no_reson_ban":"Nyo weason pwovided",
"only_server_command":"This c-c-command c-can onwy be used in a sewvew",
"purged":"Puwged {} messages",
"too_old":"Coudn't find any OwO messages youngew than 14 days?!!",
"renamed_user":"Usew <@{}> *looks at you* was wenyamed t-to {}",
"no_permission_rename":"Xyn d-doesn't have pewmission t-to wenyame this usew",
"added_spotify":"Added {} songs fwom Spotify!!",
"music_not_found":"Music nyot found",
"generic_error_music":"twack faiwed t-to woad, twy again watew\n{}",
"playlist_added":"Added {} twacks t-to the queue",
"no_voice":"You nyeed t-to be in a voice channyew t-to use this command?!!",
"added_queue":"Added t-to queue:\n[{}]({})",
"not_playing":"Thewe's nyothing pwaying?!?!",
"yet":"yet >w<",
"not_playing_tease":"Maybe you c-couwd change that ^w^",
"now_playing":"Nyow Pwaying...\n[{}]({})",
"skipped_music":"skipped t-to the nyext song:\n [{}]({})",
"resumed_music":"The pwayback was wesumed!?",
"volume_set":"Vowume set t-to {}%",
"paused":"{titwe} was paused!",
"stuck":"Weww, :3 I guess I'm stuck",
"music_stop":"Okay?!! Stopped the pwayback!",
"generic_player_error":"Unfowtunyatewy thewe was an fataw ewwow inyitiawizing the pwayew, pwease twy again watew",
"reddit_not_found":"An ewwow occuwwed t-twying t-to fetch a post fwom youw desiwed subweddit, maybe check youw spewwing ow (・`ω´・) twy again watew",
"generic_reddit_error":"Ewwow getting the sub ;;w;;",
"no_nsfw":"the safe ;;w;; mode c-can onwy be tuwnyed off inside an NSFW channyew!!",
"no_banner":"This usew has nyo bannyew!!",
"no_pfp":"This usew has nyo pfp!!",
"command_error":"An ewwow occuwed duwing the pwocessing of the command: `{}`!"
}